myapp/application/urls.py
from django.urls import path
from application import views
from application.views import chartView

app_name='application'

urlpatterns = [
    # [...]
    path('conccurent_list.html', views.home, name='home'),
    ##path('conccurent_config.html', views.conccurent_config(), name='conccurent_config')
   	path('config.html',views.config,name='config'),
   	path('config_list.html', views.ConfigList.as_view(), name='config_list'),
   	path('charts.html',chartView.as_view(), name='charts'),

]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from user_manager import views
from django.conf import settings
from django.conf.urls.static import static
from application import urls
from concurrent_api import urls
from product import urls




urlpatterns = [
    path('',views.user_login,name='login'),
    path('admin/',admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('index/',views.index,name='index'),
    path('user_manager/',include('user_manager.urls')),
    path('application/',include('application.urls')),
    path('concurrent_api/',include('concurrent_api.urls')),
    path('product/',include('product.urls'))

    



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/product/urls.py
from django.urls import path
from product import views


app_name='product'

urlpatterns = [
    # [...]
    path('product.html', views.home, name='home'),

]

myapp/user_manager/urls.py
from django.urls import path
from user_manager import views
from .views import users
from django.contrib import admin

app_name='user_manager'

urlpatterns=[
    path(r'admin/', admin.site.urls, name='admin' ),
    path('user_login/',views.user_login,name='user_login'),
    path('profile/',views.profile,name='profile'),
    path('connection/',views.formView,name='loginform'),
    path('profile/edit',views.update_profile,name='edit_profile'),
    path('register/',views.register,name='register'),

]

myapp/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Dashboard</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <link href="{% static 'charts/Chart.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'charts/Chart.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
 <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
</head>

<body id="page-top">
{% if user.is_authenticated %}
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        
        <div class="sidebar-brand-text mx-3">MIND TAB</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard 
      <hr class="sidebar-divider">

      <!-- Heading -->
      

      <!-- Nav Item - Pages Collapse Menu -->
       {% if user.is_superuser %}  
    <!-- Users -->
      <li class="nav-item ">
        <a class="nav-link collapsed" href="users.html" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-users"></i>

          <span>Admin</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
          
            <a class="collapse-item" href="{% url 'user_manager:register' %}">Register user</a>
          
            <a class="collapse-item" href="{% url 'admin:index' %}">Manager Panel</a>
            <div class="collapse-divider"></div>
            
          </div>
        </div>
      </li>
      {% endif %}
      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'application:home' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Concurrents</span></a>
      </li>
      <!-- Product -->
            <li class="nav-item">
        <a class="nav-link" href="{% url 'product:home' %}">
          <i class="fas fa-dollar-sign"></i>
          
          <span>Products</span></a>
      </li>
         <!-- configurer Dashbord -->
    
     <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Configuration</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'application:config' %}">Automatic</a>
            <a class="collapse-item" href="{% url 'application:config_list' %}">history</a>
          </div>
        </div>
      </li>


            <li class="nav-item">
        <a class="nav-link" href="{% url 'application:charts' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
     
    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          


      
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
            
             
              <!-- Users -->
               
            </li>

            <!-- Nav Item - Alerts -->
   

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                <img class="img-profile rounded-circle" src="{{ user.userprofileinfo.profile_pic.url }}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'user_manager:profile' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <!--
                <a class="dropdown-item" href="{% url 'user_manager:edit_profile' %}">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
              -->
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          {% block body_block %}

          {% endblock %}

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Masmoudi Mayssa , El Hafi Radhwene 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>
{% else %}


<h3>connecte befor ... hacker :p</h3>
{% endif %}
  <!-- Bootstrap core JavaScript-->











  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-bar-demo.js' %}"></script>

</body>

</html>