myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from user_manager import views
from django.conf import settings
from django.conf.urls.static import static
from application import urls
from concurrent_api import urls
from product import urls




urlpatterns = [
    path('',views.user_login,name='login'),
    path('admin/',admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('index/',views.index,name='index'),
    path('user_manager/',include('user_manager.urls')),
    path('application/',include('application.urls')),
    path('concurrent_api/',include('concurrent_api.urls')),
    path('product/',include('product.urls'))

    



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/user_manager/urls.py
from django.urls import path
from user_manager import views
from .views import users
from django.contrib import admin

app_name='user_manager'

urlpatterns=[
    path(r'admin/', admin.site.urls, name='admin' ),
    path('user_login/',views.user_login,name='user_login'),
    path('profile/',views.profile,name='profile'),
    path('connection/',views.formView,name='loginform'),
    path('profile/edit',views.update_profile,name='edit_profile'),
    path('register/',views.register,name='register'),

]

myapp/user_manager/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_manager = models.BooleanField(default=False)
    is_consultant = models.BooleanField(default=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username

myapp/user_manager/forms.py
from django import forms
from django.contrib.auth.models import User
from user_manager.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields =('profile_pic',)

"""
def update_profile(request):
    args = {}

    if request.method == 'POST':
        form = UpdateProfile(request.POST)
        form.actual_user = request.user
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('update_profile_success'))
    else:
        form = UpdateProfile()

    args['form'] = form
    return render(request, 'registration/update_profile.html', args)
"""

class UpdateProfile(forms.ModelForm):
	username = forms.CharField(required=True)
	email = forms.EmailField(required=True)
	first_name = forms.CharField(required=False)
	last_name = forms.CharField(required=False)

	class Meta:
	    model = User
	    fields = ('username', 'email', 'first_name', 'last_name')

	def clean_email(self):
	    username = self.cleaned_data.get('username')
	    email = self.cleaned_data.get('email')

	    if email and User.objects.filter(email=email).exclude(username=username).count():
	        raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
	    return email

	def save(self, commit=True):
	    user = super(RegistrationForm, self).save(commit=False)
	    user.email = self.cleaned_data['email']

	    if commit:
	        user.save()

	    return user

myapp/user_manager/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm,UpdateProfile

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo
from django.views.generic import ListView, DetailView
from django.contrib.auth.forms import UserChangeForm


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request,'user_manager/index.html')

    else:
        return render(request,'user_manager/accessdenide.html')

def list_users(request):
    context={
    'users':UserProfileInfoForm.objects.all()
    }
    return render(request,'user_manager/list_user.html',context)

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

class users(ListView):
    model = UserProfileInfo


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('login'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'user_manager/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.user.is_authenticated:
        return render(request,'user_manager/index.html')

    else:
        if request.method == 'POST':
            # First get the username and password supplied
            username = request.POST.get('username')
            password = request.POST.get('password')

            # Django's built-in authentication function:
            user = authenticate(username=username, password=password)

            # If we have a user
            if user:
                #Check it the account is active
                if user.is_active:
                    # Log the user in.
                    request.session['username'] = username
                    login(request,user)
                    # Send the user back to some page.
                    # In this case their homepage.
                    return HttpResponseRedirect(reverse('index'))
                else:
                    # If account is not active:
                    return HttpResponse("Your account is not active.")
            else:
                print("Someone tried to login and failed.")
                print("They used username: {} and password: {}".format(username,password))
                return HttpResponse("Invalid login details supplied.")

        else:
            #Nothing has been provided for username or password.
            return render(request, 'user_manager/login.html', {})
def formView(request):
   if request.session.has_key('username'):
      username = request.session['username']
      return render(request, 'index.html', {'username' : username})
   else:
      return render(request, 'login.html', {})
def profile(request):
    args={'user':request.user}
    return render(request,'user_manager/profile.html',args)
def chartjs(request):
    args={'chartjs':request.user}
    return render(request,'user_manager/chartjs.html',args)
def data(request):
    args={'data':request.user}
    return render(request,'user_manager/data.html',args)

"""

def edit_profile(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/user_manager/profile')
    else:
        form = UserChangeForm(instance=request.user)
        args={'form': form}
        return render(request, 'user_manager/edit_profile.html', args)
        
"""

def update_profile(request):
    args = {}

    if request.method == 'POST':
        form = UpdateProfile(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('update_profile_success'))
    else:
        form = UpdateProfile()

    args['form'] = form
    return render(request, 'user_manager/edit_profile.html', args)

myapp/templates/user_manager/accessdenide.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>error</title>
  </head>
  <body>
  <h1>Forbidden</h1>
  <h6> you dont have permission to access</h6>
  </body>
</html>

myapp/templates/user_manager/chartjs.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}

        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Charts
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Charts</a></li>
                <li class="breadcrumb-item active" aria-current="page">Chart</li>
              </ol>
            </nav>
          </div>
          <div class="row">

            <div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">product reviews</h4>
                  <canvas id="barChart" style="height:230px"></canvas>
                </div>
              </div>
            </div>


            <div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">increased product</h4>
                  <canvas id="doughnutChart" style="height:250px"></canvas>
                </div>
              </div>
            </div>


          </div>
        </div>
  {% endblock %}

myapp/templates/user_manager/data.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}

        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">
              Tables
            </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Tables</a></li>
                <li class="breadcrumb-item active" aria-current="page"></li>
              </ol>
            </nav>
          </div>
          <div class="row">
            <div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title"></h4>
                  <p class="card-description">
                    Add class <code>.table</code>
                  </p>
                  <table class="table">
                    <thead>
                      <tr>
                        <th>source</th>
                        <th>date</th>
                        <th>reactions</th>
                        <th>post_id</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Samsung</td>
                        <td>2020-02-15 13:43:01</td>
                        <td>10K</td>
                        <td>3371126999570973</td>
                      </tr>
                      <tr>
                        <td>Samsung</td>
                        <td>2020-02-14 18:47:59</td>
                        <td>110K</td>
                        <td>33711269995709732</td>
                      </tr>
                      <tr>
                        <td>Samsung</td>
                        <td>2020-02-13 12:32:43</td>
                        <td>1410K</td>
                        <td>337112699957</td>
                      </tr>
                      <tr>
                        <td>Samsung</td>
                        <td>2020-02-11 21:34:10</td>
                        <td>1610K</td>
                        <td>3371126999570973456</td>
                      </tr>
                      <tr>
                        <td>Samsung</td>
                        <td>2020-02-08 17:00:00</td>
                        <td>2010K</td>
                        <td>3371126999570973></td>
                      </tr>
                    </tbody>
                  </table>





                </div>
              </div>
            </div>
            <div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title"></h4>
                  <p class="card-description">
                    Add class <code></code>
                  </p>
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Source</th>
                        <th>reply_to</th>
                        <th>Sale</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Jacob</td>
                        <td>Photoshop</td>
                        <td class="text-danger"> 28.76% <i class="mdi mdi-arrow-down"></i></td>
                        <td><label class="badge badge-danger">Pending</label></td>
                      </tr>
                      <tr>
                        <td>Messsy</td>
                        <td>Flash</td>
                        <td class="text-danger"> 21.06% <i class="mdi mdi-arrow-down"></i></td>
                        <td><label class="badge badge-warning">In progress</label></td>
                      </tr>
                      <tr>
                        <td>John</td>
                        <td>Premier</td>
                        <td class="text-danger"> 35.00% <i class="mdi mdi-arrow-down"></i></td>
                        <td><label class="badge badge-info">Fixed</label></td>
                      </tr>
                      <tr>
                        <td>Peter</td>
                        <td>After effects</td>
                        <td class="text-success"> 82.00% <i class="mdi mdi-arrow-up"></i></td>
                        <td><label class="badge badge-success">Completed</label></td>
                      </tr>
                      <tr>
                        <td>Dave</td>
                        <td>53275535</td>
                        <td class="text-success"> 98.05% <i class="mdi mdi-arrow-up"></i></td>
                        <td><label class="badge badge-warning">In progress</label></td>
                      </tr>
                    </tbody>
                  </table>

                </div>
              </div>
            </div>
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">


                </div>
              </div>
            </div>

                </div>
              </div>
            </div>

                </div>
              </div>
            </div>


                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

myapp/templates/user_manager/edit_profile.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<div class="container">
  <div class="jumbotron">
   	<form method="post">
   		 {% csrf_token %}
   		 {% crispy form %}
   		{{ form.as_p }}
   		<button type="submit">SAVE</button>
   	</form>
  </div>
</div>

{% endblock %}

myapp/templates/user_manager/index.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
<div class="container">
  <div class="jumbotron">
    <h1>Product</h1>












  

  </div>
</div>

{% endblock %}

myapp/templates/user_manager/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css' %}">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
     <div style=" padding-top: 150px;">
    <div class="row justify-content-center">

      <div class="col-xl-5 col-lg-6 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">

            <!-- Nested Row within Card Body -->
            <div class="row justify-content-center">
              
              <div class="col-lg-12">
               
                <div class="p-5" >
                  
                    <div class="text-center">
                      <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                    </div>
                    <form class="user" action="{% url 'user_manager:user_login' %}" method="post">
                      {% csrf_token %}
                      <div class="form-group">
                        <input type="text" class="form-control form-control-user"name="username" id="username" aria-describedby="emailHelp" placeholder="username">
                      </div>
                      <div class="form-group">
                        <input type="password" class="form-control form-control-user" name="password" id="exampleInputPassword" placeholder="Password">
                      </div>
                      <div class="form-group">
                        <div class="custom-control custom-checkbox small">
                          <input type="checkbox" class="custom-control-input" id="customCheck">
                          <label class="custom-control-label" for="customCheck">Remember Me</label>
                        </div>
                      </div>
                     <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>
                    
                 
                     </form>
          
                   <div class="text-center">
                      <a class="small" href="forgot-password.html">Forgot Password?</a>
                    </div>
                    <div class="text-center">
                      <a class="small" href="register.html">Create an Account!</a>
                     </div>
                   </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

myapp/templates/user_manager/profile.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<div class="container">
  <div class="jumbotron">
     <section id="about" class="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-4" data-aos="fade-right">
            {% if user.is_authenticated %}
            <img src="{{ user.userprofileinfo.profile_pic.url }}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
            <h3>Profile</h3>
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="icofont-rounded-right"></i> <strong>UserName:</strong>{{ user.username }}</li>
                  <li><i class="icofont-rounded-right"></i> <strong>Fisrt Name:</strong>{{ user.first_name }}</li>
                  <li><i class="icofont-rounded-right"></i> <strong>Last Name:</strong> {{ user.last_name }}</li>
                  <li><i class="icofont-rounded-right"></i> <strong>Email:</strong>{{ user.email }}</li>
                </ul>
              </div>
              <div style="margin-left: 200px;
              margin-top: 480px;">
               <a href="{% url 'user_manager:edit_profile' %}">
               <button type="button" class="btn btn-primary" >edit profile</button></a>
              </div>
            </div>

          </div>

        </div>
        {% else %}
      <h3>connecte befor ... hacker :p</h3>
      {% endif %}
      </div>
  </div>
</div>

{% endblock %}

myapp/templates/user_manager/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
    {% if user.is_superuser %}
      {% if registered %}
        <h1>well registering!</h1>
      {% else %}
        <h1>ADD USER</h1>
        

        <form enctype="multipart/form-data" method="POST"  novalidate> 
        <div class="form-group">
         {% csrf_token %}
          <div class="row">
        
          <div class="col-6">
          {{ user_form.first_name|as_crispy_field }}
          </div>
          <div class="col-6">
          {{ user_form.last_name|as_crispy_field }}
          </div>
           <div class="col-6">
          {{ user_form.username|as_crispy_field }}
          </div>
           <div class="col-6">
          {{ user_form.email|as_crispy_field }}
          </div>
          
           <div class="col-6">
          {{ user_form.password|as_crispy_field }}
          </div>
          <div class="col-6">
          {{ profile_form.as_p}}
          </div>
          
          </div>
          <button type="submit" class="btn btn-primary">Save person</button>
          </div>
        </div>
        </form>

      {% endif %}
    {% endif %}
    </div>

  </div>

{% endblock %}

myapp/templates/user_manager/userprofileinfo_list.html
{% extends "base.html" %}
{% block body_block %}


 <h1 class="h3 mb-2 text-gray-800">Tables</h1>
          <p class="mb-4">List of USers </p>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">DATA</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>users</th>
                      <th>is_manager</th>
                      <th>is_consultant</th>
                
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>users</th>
                      <th>is_manager</th>
                      <th>is_consultant</th>
                    
                    </tr>
                  </tfoot>
                  <tbody>
                    {% for users in object_list %}
                    <tr>
                      <td>{{ users.user }}</td>
                      <td>{{ users.is_manager }}</td>
                      <td>{{ users.is_consultant }}</td>
                     

                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          </div>
        <!-- /.container-fluid -->
{% endblock %}